### ISSUE TITLE
get no access token

### ISSUE THREAD

**Issue by slimline33** [Flibber/Flibber#15]
Hi, I run the script for the first time because it give no access token. I think there are changes on instagram.

```
[FLIB] ----------------------
[FLIB]   Welcome to Flibber
[FLIB]   Chip (itschip.com)
[FLIB]     @ChipIsTheName
[FLIB] ----------------------

[NUM#] Request #1
[RURL] https://api.instagram.com/v1/users/self/follows
[FLDS] access_token=%3CACCESS_TOKEN_HERE%3E&client_id=*********1795ad4a9d91b7a9fc297b5e3e
[HTTP] GET
[RTRY] Retrying request...
[NUM#] Request #2
[RURL] https://api.instagram.com/v1/users/self/follows
[FLDS] access_token=%3CACCESS_TOKEN_HERE%3E&client_id=*********795ad4a9d91b7a9fc297b5e3e
[HTTP] GET
[RTRY] Retrying request...
```

what do I wrong? Do you have a solution?

**Comment by slimline33** [comment]
Found the solution after checking code: 

in flibber.py on row 256 `"if options.ACCESS_TOKEN == "":`

Have to change in options.py:

```
ACCESS_TOKEN = "<ACCESS_TOKEN_HERE>"  # CHANGE AFTER FIRST RUN
```

in

```
ACCESS_TOKEN = ""  # CHANGE AFTER FIRST RUN
```

Only remove the 

``````
<ACCESS_TOKEN_HERE>``` variable

Thanks for this fantastic script!
``````

**Comment by slimline33** [comment]
Now having the same issue like: https://github.com/Flibber/Flibber/issues/14

**Comment by tammycamp** [comment]
I did the above and having the same issue:

Traceback (most recent call last):
  File "flibber.py", line 700, in <module>
    begin()
  File "flibber.py", line 686, in begin
    getAccessToken()
  File "flibber.py", line 264, in getAccessToken
    options.ACCESS_TOKEN = str(data["access_token"])
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by amiruqdah** [comment]
**NOTE:** Before you waste your time with this script, know that Instagram's new changes to the API have _completely_ outdated Flibber. In fact, the "likes" and "relationships" endpoints are now restricted so in order to actually gain access to these endpoints you have to be a "well established business". Here's the official [form](https://help.instagram.com/contact/185819881608116#)

@tammycamp I just had to use this script for a client of mine, and the best way to get around this is to simply do it via your browser. The process is relatively simple and if you follow the process [here](http://jelled.com/instagram/access-token) you can fill out the required variables without much trouble.

A quick caveat, however. You'll need to pay attention to the response_type query parameter. **Before** you get the access token for your application you should get your application's code. That can be done by easily running the following in your browser, after adding localhost(make sure you don't put .com at the end) to your approved list of redirect url's.

## Get Code Response

`https://api.instagram.com/oauth/authorize/?client_id=<CLIENT_ID_HERE>&redirect_uri=http://localhost&response_type=code&display=touch&scope=likes+relationships`

## Get Access Token

`https://api.instagram.com/oauth/authorize/?client_id=<CLIENT_ID_HERE>&redirect_uri=http://localhost&response_type=token&display=touch&scope=likes+relationships`

Hope this helps you out a bit! :grin:
